<?php
/**
 * Created by PhpStorm.
 * User: guozhenming
 * Date: 2018/10/18
 * Time: 2:02 PM
 */

namespace frontend\components;

use yii\base\ActionFilter;

class ActionTimeFilter extends ActionFilter
{
    private $_startTime;

    public function beforeAction($action)
    {
        $this->_startTime = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $time = microtime(true) - $this->_startTime;
        \Yii::debug("Action '{$action->uniqueId}' send $time second.");
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}
